variables:
  azureSubscriptionEndpoint: devops
  azureContainerRegistry: '{"loginServer":"victoryw.azurecr.io", "id" : "/subscriptions/fa5339f8-494f-4c65-8d85-6bfc495b151a/resourceGroups/container/providers/Microsoft.ContainerRegistry/registries/victoryw"}'
  dockerComposeFile: docker-compose-build.yml

trigger:
- master
stages:
  - stage: 'test'
    jobs:
      - job: 'test_package_build_service'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: Maven@3
          displayName: test jar
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'test'
      - job: 'build_docker_image'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: Maven@3
          displayName: Build jar
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: '-Dmaven.test.skip=true package'
        - task: DockerCompose@0
          displayName: Build services
          inputs:
            action: Build services
            azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
            azureContainerRegistry: $(azureContainerRegistry)
            dockerComposeFile: $(dockerComposeFile)
            projectName: $(Build.Repository.Name)
            qualifyImageNames: true
            additionalImageTags: $(Build.BuildId)
        - task: DockerCompose@0
          displayName: Push services
          inputs:
            action: Push services
            containerregistrytype: 'Azure Container Registry'
            azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
            azureContainerRegistry: $(azureContainerRegistry)
            dockerComposeFile: $(dockerComposeFile)
            additionalImageTags: $(Build.BuildId)
      - job: 'upload_k8s_file'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/k8s'
            artifact: 'k8s'  
  - stage: 'deploy_service'
    jobs:
      - deployment: 'deploy'
        environment: 'victoryw-dubbo-contract-test-dev'
        pool:
          vmImage: 'ubuntu-latest'
        strategy: 
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifact: 'k8s'
                  targetPath: '$(System.DefaultWorkingDirectory)/k8s'
              - task: KubernetesManifest@0
                inputs:
                  action: 'deploy'
                  kubernetesServiceConnection: 'dubbo-contract-test-k8s'
                  namespace: 'default'
                  manifests: 'k8s/*'