apiVersion: v1
kind: Service
metadata:
  labels:
    service:  dubbo-contract-test-consumer
  name:  dubbo-contract-test-consumer
spec:
  type: LoadBalancer
  ports:
  - name: http-port
    port: 8080
  selector:
    app: dubbo-contract-test-consumer
