apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  type: LoadBalancer
  selector:
    app: zookeeper
  ports:
    - name: zookeeper-client-ip
      protocol: TCP
      port: 2181
      targetPort: 2181

